// Code generated by github.com/dashotv/golem. DO NOT EDIT.
package client

import (
	"github.com/dashotv/flame/nzbget"
	"github.com/dashotv/flame/qbt"
)

type Combined struct { // struct
	Torrents  []*qbt.Torrent `bson:"torrents" json:"torrents"`
	Nzbs      []nzbget.Group `bson:"nzbs" json:"nzbs"`
	NzbStatus *nzbget.Status `bson:"nzb_status" json:"nzb_status"`
	Metrics   *Metrics       `bson:"metrics" json:"metrics"`
}

type Metrics struct { // struct
	Diskspace string        `bson:"diskspace" json:"diskspace"`
	Torrents  *TorrentRates `bson:"torrents" json:"torrents"`
	Nzbs      *NzbRates     `bson:"nzbs" json:"nzbs"`
}

type NzbRates struct { // struct
	DownloadRate string `bson:"download_rate" json:"download_rate"`
}

type TorrentRates struct { // struct
	DownloadRate string `bson:"download_rate" json:"download_rate"`
	UploadRate   string `bson:"upload_rate" json:"upload_rate"`
}
