mode: release
port: 9001
cron: true
Qbittorrent:
  URL: http://qbittorrent.dasho.net/
  Username: admin
  Password: adminadmin
Nzbget:
  URL: http://nzbget.dasho.net/jsonrpc
Nats:
  URL: nats://dashotv-nats-1:4222
Redis:
  host: dashotv-redis-1
  port: 6379
  database: 15
connections:
  default:
    uri: mongodb://db:27017
    database: database
  download:
    database: seer_development
    collection: downloads
  media:
    database: seer_development
    collection: media
