mode: release
port: 9001
Qbittorrent:
  URL: http://qbittorrent.dasho.net/
  Username: admin
  Password: adminadmin
Nzbget:
  URL: http://nzbget.dasho.net/jsonrpc
Nats:
  URL: nats://nats:680a4c58fbbc180b1f2d7a1beab63491@dokku-nats-nats:4222
connections:
  default:
    uri: mongodb://localhost:27017
    database: database
  download:
    database: seer_development
    collection: downloads
