// This file is autogenerated by Golem
// Do NOT make modifications, they will be lost
package downloads

import (
	"github.com/gin-gonic/gin"

	"github.com/dashotv/flame/application"
	"github.com/dashotv/flame/config"
)

var cfg *config.Config
var app *application.App

func Routes() {
	cfg = config.Instance()
	app = application.Instance()

	r := app.Router.Group("/downloads")
	r.GET("/", indexHandler)

}

func indexHandler(c *gin.Context) {

	Index(c)
}
