mode: release
port: 9001
cron: true
Qbittorrent:
  URL: http://qbittorrent.dasho.net/
  Username: admin
  Password: adminadmin
Nzbget:
  URL: http://nzbget.dasho.net/jsonrpc
Nats:
  URL: nats://host.docker.internal:4222
Redis:
  host: host.docker.internal
  port: 6379
  database: 15
connections:
  default:
    uri: mongodb://host.docker.internal:27017
    database: database
  download:
    database: seer_production
    collection: downloads
  media:
    database: seer_production
    collection: media
