// Code generated by github.com/dashotv/golem. DO NOT EDIT.
package app

import (
	"context"

	"go.elastic.co/apm/module/apmechov4/v2"
)

func init() {
	starters = append(starters, startAPM)
}

func startAPM(ctx context.Context, a *Application) error {
	a.Engine.Use(apmechov4.Middleware())
	a.Default.Use(apmechov4.Middleware())
	a.Router.Use(apmechov4.Middleware())
	return nil
}
