version: "2.0"
name: flame
repo: github.com/dashotv/flame
package: app
output: app
plugins:
  models: false
  routes: true
  workers: true
  cache: true
  events: true
definitions:
  models: .golem/models
  routes: .golem/routes
  events: .golem/events
  workers: .golem/workers
  queues: .golem/queues
